// Benchmarks system libm accuracy and performance.
// Uses the same test data and scoring as the JS benchmark.
//
// Build: cd c && make && ./bench-libm

#include <math.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <time.h>

// --- Timing ---

static double now_ms(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec * 1000.0 + ts.tv_nsec / 1e6;
}

// --- ULP computation ---

static double ulp_of(double x) {
    if (!isfinite(x) || x == 0.0) return 0.0;
    uint64_t bits;
    memcpy(&bits, &x, sizeof(bits));
    bits &= 0x7FFFFFFFFFFFFFFFull;
    int exp_bits = (int)((bits >> 52) & 0x7FF);
    if (exp_bits == 0) return 5e-324;
    return ldexp(1.0, exp_bits - 1075);
}

static double ulp_error(double computed, double expected) {
    if (isnan(expected) && isnan(computed)) return 0.0;
    if (isnan(expected) || isnan(computed)) return INFINITY;
    if (expected == computed) return 0.0;
    if (!isfinite(expected) || !isfinite(computed)) return INFINITY;
    if (expected == 0.0) {
        if (computed == 0.0) return 0.0;
        return fabs(computed) / 5e-324;
    }
    return fabs(computed - expected) / ulp_of(expected);
}

// --- PRNG (same as bench.js mulberry32) ---

static uint32_t prng_state;
static void prng_seed(uint32_t s) { prng_state = s; }
static double prng_next(void) {
    prng_state += 0x6D2B79F5u;
    uint32_t t = prng_state;
    t = (t ^ (t >> 15)) * (1u | t);
    t = (t + ((t ^ (t >> 7)) * (61u | t))) ^ t;
    return (double)((t ^ (t >> 14)) >> 0) / 4294967296.0;
}

// --- Test data (generated by generate-libm-bench.js) ---
//
// The .inc file defines, for each function, a DATA_<name> macro that expands
// a visitor over its test categories.  For a unary function:
//
//   DATA_cbrt(V, name)  expands to:
//     V(name, worstCase, 1000, testdata_cbrt_worstCase_in, testdata_cbrt_worstCase_out, _, _)
//     V(name, systematic, 250, testdata_cbrt_systematic_in, testdata_cbrt_systematic_out, _, _)
//     V(name, edgeCases, 27, testdata_cbrt_edgeCases_in, testdata_cbrt_edgeCases_out, _, _)
//
// For a binary function, the a/b arrays replace the in/_ slots:
//
//   DATA_atan2(V, name)  expands to:
//     V(name, worstCase, 1000, _, testdata_atan2_worstCase_out, testdata_atan2_worstCase_a, testdata_atan2_worstCase_b)
//     ...

#include "bench-libm-data.inc"

// --- Function table using X-macros ---

#define FOR_EACH_FUNCTION(UNARY, BINARY) \
    UNARY(acos)  UNARY(acosh) UNARY(asin) UNARY(asinh) \
    UNARY(atan)  BINARY(atan2) UNARY(atanh) \
    UNARY(cbrt)  UNARY(cos)   UNARY(cosh) \
    UNARY(exp)   UNARY(expm1) \
    UNARY(log)   UNARY(log1p) UNARY(log2) UNARY(log10) \
    BINARY(pow) \
    UNARY(sin)   UNARY(sinh)  UNARY(sqrt) \
    UNARY(tan)   UNARY(tanh)

// --- Accuracy ---

typedef struct {
    const char *fn;
    int count;
    double max_ulp, mean_ulp;
    double correctly_rounded_pct, faithfully_rounded_pct;
    char worst_input[128];
    double worst_expected, worst_computed;
} AccuracyResult;

static void accuracy_add(AccuracyResult *r, double computed, double expected,
                         const char *fmt, ...) {
    double ulp = ulp_error(computed, expected);
    double capped = ulp < 1e15 ? ulp : 1e15;
    r->mean_ulp += capped;  // sum; divided by count later
    if (ulp <= 0.5) r->correctly_rounded_pct += 1;  // count; converted later
    if (ulp <= 1.0) r->faithfully_rounded_pct += 1;
    if (ulp > r->max_ulp || (isinf(ulp) && !isinf(r->max_ulp))) {
        r->max_ulp = ulp;
        r->worst_expected = expected;
        r->worst_computed = computed;
        va_list ap;
        va_start(ap, fmt);
        vsnprintf(r->worst_input, sizeof(r->worst_input), fmt, ap);
        va_end(ap);
    }
    r->count++;
}

#define ACCURACY_UNARY(name, cat, n, in, out, a, b) \
    for (int i = 0; i < n; i++) \
        accuracy_add(&r, name(in[i]), out[i], "%a", in[i]);

#define ACCURACY_BINARY(name, cat, n, in, out, a, b) \
    for (int i = 0; i < n; i++) \
        accuracy_add(&r, name(a[i], b[i]), out[i], "%a, %a", a[i], b[i]);

#define RUN_ACCURACY_UNARY(name) \
    if (strcmp(fn_name, #name) == 0) { DATA_##name(ACCURACY_UNARY, name) }
#define RUN_ACCURACY_BINARY(name) \
    if (strcmp(fn_name, #name) == 0) { DATA_##name(ACCURACY_BINARY, name) }

static AccuracyResult run_accuracy(const char *fn_name) {
    AccuracyResult r = {fn_name, 0, 0.0, 0.0, 0.0, 0.0, "", 0.0, 0.0};
    FOR_EACH_FUNCTION(RUN_ACCURACY_UNARY, RUN_ACCURACY_BINARY)
    if (r.count > 0) {
        r.correctly_rounded_pct = r.correctly_rounded_pct / r.count * 100.0;
        r.faithfully_rounded_pct = r.faithfully_rounded_pct / r.count * 100.0;
        r.mean_ulp = r.mean_ulp / r.count;
    }
    return r;
}

// --- Performance ---

typedef struct {
    const char *fn;
    double avg_ops_per_sec, perf_bonus;
} PerfResult;

#define PERF_N 100000
#define MIN_TIME_MS 10.0
#define PERF_ROUNDS 3
#define REFERENCE_RATE 1000e6

// One loop function per math function for monomorphic calls.
#define DEFINE_PERF_UNARY(name) \
    static double perf_loop_##name(const double *a, int n) { \
        double d = 0; \
        for (int i = 0; i < n; i++) d += name(a[i]); \
        return d; \
    }
#define DEFINE_PERF_BINARY(name) \
    static double perf_loop_##name(const double *a, const double *b, int n) { \
        double d = 0; \
        for (int i = 0; i < n; i++) d += name(a[i], b[i]); \
        return d; \
    }

FOR_EACH_FUNCTION(DEFINE_PERF_UNARY, DEFINE_PERF_BINARY)

static double measure_unary(double (*loop)(const double *, int),
                            const double *a) {
    volatile double dummy = 0;
    for (int w = 0; w < 5; w++) dummy += loop(a, PERF_N);

    double samples[PERF_ROUNDS];
    for (int r = 0; r < PERF_ROUNDS; r++) {
        long total_ops = 0;
        double d = 0;
        double start = now_ms();
        double deadline = start + MIN_TIME_MS;
        while (now_ms() < deadline) {
            d += loop(a, PERF_N);
            total_ops += PERF_N;
        }
        dummy += d;
        samples[r] = (double)total_ops / (now_ms() - start) * 1000.0;
    }
    if (samples[0] > samples[1]) { double t = samples[0]; samples[0] = samples[1]; samples[1] = t; }
    if (samples[1] > samples[2]) { double t = samples[1]; samples[1] = samples[2]; samples[2] = t; }
    if (samples[0] > samples[1]) { double t = samples[0]; samples[0] = samples[1]; samples[1] = t; }
    return samples[1];
}

static double measure_binary(double (*loop)(const double *, const double *, int),
                             const double *a, const double *b) {
    volatile double dummy = 0;
    for (int w = 0; w < 5; w++) dummy += loop(a, b, PERF_N);

    double samples[PERF_ROUNDS];
    for (int r = 0; r < PERF_ROUNDS; r++) {
        long total_ops = 0;
        double d = 0;
        double start = now_ms();
        double deadline = start + MIN_TIME_MS;
        while (now_ms() < deadline) {
            d += loop(a, b, PERF_N);
            total_ops += PERF_N;
        }
        dummy += d;
        samples[r] = (double)total_ops / (now_ms() - start) * 1000.0;
    }
    if (samples[0] > samples[1]) { double t = samples[0]; samples[0] = samples[1]; samples[1] = t; }
    if (samples[1] > samples[2]) { double t = samples[1]; samples[1] = samples[2]; samples[2] = t; }
    if (samples[0] > samples[1]) { double t = samples[0]; samples[0] = samples[1]; samples[1] = t; }
    return samples[1];
}

#define RUN_PERF_UNARY(name) \
    if (strcmp(fn_name, #name) == 0) { \
        double sets[3][PERF_N]; \
        prng_seed(0x12345678u); \
        for (int i = 0; i < PERF_N; i++) sets[0][i] = prng_next(); \
        for (int i = 0; i < PERF_N; i++) sets[1][i] = prng_next() * 20.0 - 10.0; \
        for (int i = 0; i < PERF_N; i++) sets[2][i] = (double)i; \
        for (int s = 0; s < 3; s++) \
            total += measure_unary(perf_loop_##name, sets[s]); \
    }

#define RUN_PERF_BINARY(name) \
    if (strcmp(fn_name, #name) == 0) { \
        double a[3][PERF_N], b[3][PERF_N]; \
        prng_seed(0x12345678u); \
        for (int i = 0; i < PERF_N; i++) { a[0][i] = prng_next(); b[0][i] = prng_next(); } \
        for (int i = 0; i < PERF_N; i++) { a[1][i] = prng_next()*20-10; b[1][i] = prng_next()*20-10; } \
        for (int i = 0; i < PERF_N; i++) { a[2][i] = (double)((int)(prng_next()*1000)); b[2][i] = (double)((int)(prng_next()*1000)); } \
        for (int s = 0; s < 3; s++) \
            total += measure_binary(perf_loop_##name, a[s], b[s]); \
    }

static PerfResult run_perf(const char *fn_name) {
    PerfResult r = {fn_name, 0.0, 0.0};
    double total = 0;
    FOR_EACH_FUNCTION(RUN_PERF_UNARY, RUN_PERF_BINARY)
    r.avg_ops_per_sec = total / 3.0;
    r.perf_bonus = r.avg_ops_per_sec / REFERENCE_RATE * 20.0;
    if (r.perf_bonus > 20.0) r.perf_bonus = 20.0;
    return r;
}

// --- Output ---

static void format_ops(double ops, char *buf, int bufsize) {
    if (ops >= 1e9) snprintf(buf, bufsize, "%.1fB", ops / 1e9);
    else if (ops >= 1e6) snprintf(buf, bufsize, "%.1fM", ops / 1e6);
    else if (ops >= 1e3) snprintf(buf, bufsize, "%.1fK", ops / 1e3);
    else snprintf(buf, bufsize, "%.0f", ops);
}

#define NAME_ENTRY(name) #name,

int main(void) {
    const char *functions[] = {
        FOR_EACH_FUNCTION(NAME_ENTRY, NAME_ENTRY)
    };
    int nfns = sizeof(functions) / sizeof(functions[0]);

    printf("Running libm benchmark...\n\n");
    printf("%-14s%10s%12s%8s%8s%10s%14s%8s%8s\n",
           "Function", "Max ULP", "Mean ULP", "% CR", "% FR",
           "Accuracy", "Ops/sec", "Perf+", "Total");
    for (int i = 0; i < 110; i++) putchar('-');
    putchar('\n');

    double log_sum = 0.0;
    int score_count = 0;

    for (int f = 0; f < nfns; f++) {
        const char *fn = functions[f];
        AccuracyResult a = run_accuracy(fn);
        PerfResult p = run_perf(fn);

        double accuracy_score = 100.0 / (1.0 + a.mean_ulp);
        double total = accuracy_score + p.perf_bonus;

        char max_ulp_str[32];
        if (isinf(a.max_ulp)) snprintf(max_ulp_str, sizeof(max_ulp_str), "Inf");
        else snprintf(max_ulp_str, sizeof(max_ulp_str), "%.2f", a.max_ulp);

        char ops_str[32];
        format_ops(p.avg_ops_per_sec, ops_str, sizeof(ops_str));

        char fn_label[32];
        snprintf(fn_label, sizeof(fn_label), "%s()", fn);

        printf("%-14s%10s%12.4f%7.1f%%%7.1f%%%10.1f%14s%8.1f%8.1f\n",
               fn_label, max_ulp_str, a.mean_ulp,
               a.correctly_rounded_pct, a.faithfully_rounded_pct,
               accuracy_score, ops_str, p.perf_bonus, total);
        if (a.max_ulp > 0) {
            printf("%-14s  ^ input: %s  expected: %a  got: %a\n",
                   "", a.worst_input, a.worst_expected, a.worst_computed);
        }

        if (total > 0) {
            log_sum += log(total);
            score_count++;
        }
    }

    for (int i = 0; i < 110; i++) putchar('=');
    putchar('\n');
    printf("\nOverall Score: %.1f\n",
           score_count > 0 ? exp(log_sum / score_count) : 0.0);

    return 0;
}
